services:
  servico-funcionarios:
    build: ./servico-funcionarios
    ports:
      - "8000:8000"
    env_file:
      - ./servico-funcionarios/.env
    depends_on:
      - funcionarios-db

  funcionarios-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funcionarios_db
    ports:
      - "5432:5432"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - servico-funcionarios
